echo "# Stacks-Bitcoin Double Node on Docker" >> README.md
git init
git add "stacks-node/config/mainnet/Config.toml" 
git commit -m "testing"
git add . && git push
git branch -M master
git remote add origin http://github.com/ungtb10d/ludotriks
git push -u origin master
